namespace EmergencyEvents.RemoteAdminCommands;

/// <summary>
/// 统一根命令支持的无副作用语法类型。
/// </summary>
public enum EmergencyEventsCommandKind
{
    Invalid,
    Help,
    Status,
    Enable,
    Disable,
    Version,
    Config,
    Health,
    Modules,
    ModuleDetail,
    Round,
    WaveState,
    WaveCurrent,
    WaveLast,
    WavePrevious,
    WaveHistory,
    WaveHistoryDetail,
    WaveTimers,
    WaveCap,
    WaveSurvival,
    DlrcState,
    DlrcEvaluate,
    DlrcStage,
    DlrcStageFull,
    DlrcStageRaw,
    DlrcBreakdown,
    DlrcControl,
    DlrcHistory,
    DlrcSnapshot,
    CrisisState,
    CrisisList,
    CrisisCheck,
    TestCrisisAll,
    TestCrisisCheck,
    TestCrisisBioZombies,
    TestCrisisSysTier,
    TestCrisisSec,
    TestCrisisWar,
    TestCrisisConCheckpoint,
    TestCrisisConCheckpointCommit,
    TestCrisisEndCheck,
    TestCrisisEndSimulate,
    Cleanup,
    TestCleanupVerify,
}
